# -*- coding: utf-8 -*-
"""함수 단위 IPO. (함수ID, 함수명, 모듈ID, 기능ID, 입력, 처리, 출력,
호출자, 호출대상, 외부I/O, 구현위치, 근거)

근거의 F# 는 코드의 [F#] 실행 흐름 주석과 1:1 대응한다.
"""

FUNCS = [
 # ── FN01 Gemini API Key 입력 ────────────────────────────
 ("FUNC001", "onSubmit()", "M1", "FN01", "폼 입력 문자열",
  "입력값을 유스케이스에 전달하고 결과로 화면을 분기한다", "저장 완료 카드 또는 오류 메시지",
  "사용자 이벤트 (제출)", "enterWithApiKey()", "없음",
  "components/start/api-key-form.tsx :: onSubmit() :F5",
  "components/start/api-key-form.tsx:F5"),
 ("FUNC002", "enterWithApiKey()", "M1", "FN01", "raw, store",
  "checkApiKey() 로 검증 후 통과 시 저장소에 기록하고 실패 사유를 구분한다",
  "{ok:true,key} 또는 {ok:false,problem|reason}", "onSubmit()",
  "checkApiKey() · browserApiKeyStore.save()", "없음",
  "lib/usecase/enter-with-api-key.ts :: enterWithApiKey() :F1",
  "lib/usecase/enter-with-api-key.ts:F1"),
 ("FUNC003", "checkApiKey()", "M1", "FN01", "raw: string",
  "공백을 제거하고 빈 값 여부를 판정한다", "{ok:true,key} 또는 problem:'empty'",
  "enterWithApiKey() · app/api/chat/route.ts", "없음", "없음",
  "lib/domain/api-key.ts :: checkApiKey() :F1", "lib/domain/api-key.ts:F1"),
 ("FUNC004", "browserApiKeyStore.save()", "M1", "FN01", "key",
  "브라우저 저장소에 Key 를 기록한다", "boolean", "enterWithApiKey()", "없음",
  "▷ localStorage 'cookpilot.gemini-key'",
  "lib/adapter/browser-api-key-store.ts :: save() :F4",
  "lib/adapter/browser-api-key-store.ts:F4"),
 ("FUNC005", "findSavedKey()", "M1", "FN01", "store",
  "저장된 Key 를 조회한다. 읽기 실패는 미보유와 동일하게 처리한다", "ApiKey 또는 null",
  "home-me · live-console · cook-shell · pick-cards · ask-shell", "store.load()",
  "▷ localStorage", "lib/usecase/enter-with-api-key.ts :: findSavedKey() :F7",
  "lib/usecase/enter-with-api-key.ts:F7"),
 ("FUNC006", "forgetSavedKey()", "M1", "FN01", "store",
  "저장된 Key 를 삭제한다", "없음", "onChangeKey() · pick-rail", "store.clear()",
  "▷ localStorage", "lib/usecase/enter-with-api-key.ts :: forgetSavedKey() :F8",
  "lib/usecase/enter-with-api-key.ts:F8"),
 ("FUNC007", "maskApiKey()", "M1", "FN01", "key",
  "화면 표시용으로 Key 가운데를 가린다", "가려진 문자열", "api-key-form", "없음", "없음",
  "lib/domain/api-key.ts :: maskApiKey() :F5", "lib/domain/api-key.ts:F5"),

 # ── FN02 로그인 · 회원가입 ──────────────────────────────
 ("FUNC008", "signInAction()", "M2", "FN02", "prev, formData",
  "폼 값을 추출해 로그인 유스케이스를 호출하고 성공 시 캐시를 무효화한 뒤 이동시킨다",
  "AuthFormState 또는 redirect('/start')", "components/login/login-form.tsx",
  "signIn() · revalidatePath() · redirect()", "없음",
  "app/actions/auth.ts :: signInAction() :F2", "app/actions/auth.ts:F2"),
 ("FUNC009", "signIn()", "M2", "FN02", "rawEmail, rawPassword, gateway",
  "자격 증명을 검증하고 통과한 경우에만 인증 게이트웨이를 호출한다",
  "{ok:true,email} 또는 오류 코드", "signInAction()",
  "checkCredentials() · supabaseAuthGateway.signIn()", "없음",
  "lib/usecase/sign-in.ts :: signIn() :F1", "lib/usecase/sign-in.ts:F1"),
 ("FUNC010", "checkCredentials()", "M2", "FN02", "rawEmail, rawPassword",
  "빈 값 · @ 포함 여부 · 빈 비밀번호를 순서대로 검사한다",
  "{ok:true,email,password} 또는 problem", "signIn()", "없음", "없음",
  "lib/domain/credentials.ts :: checkCredentials() :F1", "lib/domain/credentials.ts:F1"),
 ("FUNC011", "supabaseAuthGateway.signIn()", "M2", "FN02", "email, password",
  "인증을 요청하고 오류를 메일 미확인 · 요청 과다 · 그 외로 분류한다",
  "{ok:true} 또는 {ok:false,reason}", "signIn()", "없음", "▷ Supabase Auth",
  "lib/adapter/supabase-auth-gateway.ts :: signIn() :F4",
  "lib/adapter/supabase-auth-gateway.ts:F4"),
 ("FUNC012", "signUpAction()", "M2", "FN02", "prev, formData",
  "가입 폼 값을 추출해 가입 유스케이스를 호출하고 메일 확인 필요 여부로 분기한다",
  "AuthFormState 또는 redirect('/start')", "components/signup/signup-form.tsx",
  "signUp() · redirect()", "없음",
  "app/actions/auth.ts :: signUpAction() :F8", "app/actions/auth.ts:F8"),
 ("FUNC013", "signUp()", "M2", "FN02", "rawName, rawEmail, rawPassword, rawConfirm, gateway",
  "표시 이름과 가입 자격 증명을 검증하고 통과 시 가입을 요청한다",
  "{ok:true,needsConfirm} 또는 오류 코드", "signUpAction()",
  "checkDisplayName() · checkNewCredentials() · supabaseAuthGateway.signUp()", "없음",
  "lib/usecase/sign-up.ts :: signUp() :F1", "lib/usecase/sign-up.ts:F1"),
 ("FUNC014", "checkNewCredentials()", "M2", "FN02", "rawEmail, rawPassword, rawConfirm",
  "로그인 검증에 더해 8자 미만과 확인 필드 불일치를 검사한다", "{ok:true,...} 또는 problem",
  "signUp()", "없음", "없음",
  "lib/domain/credentials.ts :: checkNewCredentials() :F8", "lib/domain/credentials.ts:F8"),
 ("FUNC015", "checkDisplayName()", "M2", "FN02", "raw: string",
  "표시 이름 길이와 형식을 판정한다", "{ok:true,name} 또는 problem",
  "signUp() · renameMe()", "없음", "없음",
  "lib/domain/display-name.ts :: checkDisplayName() :F1", "lib/domain/display-name.ts:F1"),
 ("FUNC016", "supabaseAuthGateway.signUp()", "M2", "FN02", "name, email, password",
  "계정 생성을 요청한다. 프로필 행은 테이블 트리거가 생성한다",
  "{ok:true,needsConfirm} 또는 오류 코드", "signUp()", "없음", "▷ Supabase Auth",
  "lib/adapter/supabase-auth-gateway.ts :: signUp() :F8",
  "lib/adapter/supabase-auth-gateway.ts:F8"),
 ("FUNC017", "signOutAction()", "M2", "FN02", "없음",
  "세션을 종료하고 캐시를 무효화한 뒤 로그인 화면으로 이동시킨다", "redirect('/login')",
  "화면 로그아웃 버튼", "supabaseSignOut()", "▷ Supabase Auth",
  "app/actions/auth.ts :: signOutAction() :F14", "app/actions/auth.ts:F14"),
 ("FUNC018", "currentUserEmail()", "M2", "FN02", "없음",
  "현재 로그인한 사용자의 이메일을 조회한다. 접근 권한 검사의 기준값이다",
  "email 또는 null", "app/write · app/account · app/posts/[id] · app/community",
  "없음", "▷ Supabase Auth",
  "lib/adapter/supabase-auth-gateway.ts :: currentUserEmail() :F12",
  "lib/adapter/supabase-auth-gateway.ts:F12"),

 # ── FN03 음성 입력 레시피 생성 ──────────────────────────
 ("FUNC019", "start()", "M3", "FN03", "없음 (마이크 버튼)",
  "마이크를 열어 PCM 조각을 수집하고 재클릭 시 WAV base64 로 변환한다", "clip",
  "사용자 이벤트 (마이크)", "openMic() · toBase64() · planFromSpeech()", "▷ 마이크",
  "components/pick/voice-console.tsx :: start() :F6",
  "components/pick/voice-console.tsx:F6"),
 ("FUNC020", "openMic()", "M3", "FN03", "없음",
  "마이크 권한을 확인하고 워크릿으로 Float32 를 pcm16 으로 변환해 흘려보낸다",
  "MicResult (핸들) 또는 오류 코드", "voice-console · live-console", "없음",
  "▷ getUserMedia", "lib/adapter/browser-audio.ts :: openMic() :F2",
  "lib/adapter/browser-audio.ts:F2"),
 ("FUNC021", "toBase64()", "M3", "FN03", "bytes: Uint8Array",
  "바이트 배열을 base64 문자열로 변환한다", "base64 문자열", "wavBase64()", "없음", "없음",
  "lib/adapter/browser-audio.ts :: toBase64() :F17", "lib/adapter/browser-audio.ts:F17"),
 ("FUNC022", "planFromSpeech()", "M3", "FN03", "clip, servings, gateway, store",
  "음성 길이 하한을 검사하고 통과 시 모델을 호출해 레시피를 생성한 뒤 기록한다",
  "{ok:true,recipe} 또는 오류 코드", "voice-console",
  "gateway.fromSpeech() · finish()", "없음",
  "lib/usecase/plan-recipe.ts :: planFromSpeech() :F1", "lib/usecase/plan-recipe.ts:F1"),
 ("FUNC023", "call()", "M3", "FN03", "parts, system, schema",
  "responseSchema 를 지정해 생성 요청을 보내고 200 이 아니면 오류 코드로 분류한다",
  "parsed JSON 또는 오류 코드", "ask() · fridgeIdeas()", "없음", "▷ Gemini REST",
  "lib/adapter/gemini-recipe-gateway.ts :: call() :F5",
  "lib/adapter/gemini-recipe-gateway.ts:F5"),
 ("FUNC024", "readRecipe()", "M3", "FN03", "value: unknown, fallbackServings",
  "재료와 조리 단계 중 유효 항목만 수집하고 출처를 판정해 Recipe 로 변환한다",
  "{ok:true,recipe} 또는 problem", "ask() · shelf-stand", "readSource()", "없음",
  "lib/domain/recipe.ts :: readRecipe() :F3", "lib/domain/recipe.ts:F3"),
 ("FUNC025", "readSource()", "M3", "FN03", "value: unknown",
  "youtube(url 필수) · shelf · community(chef 필수) · 그 외로 출처를 판정한다",
  "RecipeSource", "readRecipe()", "없음", "없음",
  "lib/domain/recipe.ts :: readSource() :F15", "lib/domain/recipe.ts:F15"),
 ("FUNC026", "finish()", "M3", "FN03", "answer, store",
  "생성 결과가 성공이면 임시 레시피로 기록한다", "{ok:true,recipe} 또는 오류 코드",
  "planFromSpeech() · planFromDish() · planFromYoutube() · planFromFridgeIdea()",
  "browserRecipeDraftStore.save()", "▷ localStorage",
  "lib/usecase/plan-recipe.ts :: finish() :F14", "lib/usecase/plan-recipe.ts:F14"),
 ("FUNC027", "findDraft()", "M3", "FN03", "store",
  "기록된 임시 레시피를 조회한다", "Recipe 또는 null",
  "shop-shell · cook-shell · done-shell · write-form", "store.load()", "▷ localStorage",
  "lib/usecase/plan-recipe.ts :: findDraft() :F18", "lib/usecase/plan-recipe.ts:F18"),
 ("FUNC028", "forgetDraft()", "M3", "FN03", "store",
  "임시 레시피를 삭제한다. 요리 완료 후 다음 요리 선택 시 호출된다", "없음",
  "components/cook/done-shell.tsx (F 미부여)", "store.clear()", "▷ localStorage",
  "lib/usecase/plan-recipe.ts :: forgetDraft() :F19", "lib/usecase/plan-recipe.ts:F19"),
 ("FUNC029", "searchUrl()", "M3", "FN03", "mall, keyword",
  "쇼핑몰별 검색 URL 을 조립한다", "URL 문자열", "shop-shell · done-shell", "없음", "없음",
  "lib/domain/shopping.ts :: searchUrl() :F2", "lib/domain/shopping.ts:F2"),

 # ── FN04 YouTube 링크 레시피 생성 ───────────────────────
 ("FUNC030", "run()", "M3", "FN04", "raw(URL), servings",
  "입력 방식에 따라 유스케이스를 호출하고 성공 시 장보기 화면으로 이동시킨다", "없음",
  "사용자 이벤트 (가져오기)", "planFromYoutube() · findFridgeIdeas()", "없음",
  "components/pick/pick-cards.tsx :: run() :F6", "components/pick/pick-cards.tsx:F6"),
 ("FUNC031", "planFromYoutube()", "M3", "FN04", "raw, servings, gateway, store",
  "URL 을 먼저 검증해 실패 시 모델을 호출하지 않고, 통과 시 영상에서 레시피를 옮긴다",
  "{ok:true,recipe} 또는 오류 코드", "run()",
  "readYoutubeUrl() · gateway.fromYoutube() · finish()", "없음",
  "lib/usecase/plan-recipe.ts :: planFromYoutube() :F8", "lib/usecase/plan-recipe.ts:F8"),
 ("FUNC032", "readYoutubeUrl()", "M3", "FN04", "raw: string",
  "URL 파싱 후 host 가 youtube.com · youtu.be 인지 검사한다",
  "{ok:true,url} 또는 'empty'|'not-youtube'", "planFromYoutube()", "없음", "없음",
  "lib/domain/recipe.ts :: readYoutubeUrl() :F22", "lib/domain/recipe.ts:F22"),
 ("FUNC033", "fromYoutube()", "M3", "FN04", "url, servings",
  "영상 URL 을 fileData 로 전달해 레시피를 생성하고 출처 정보를 부착한다",
  "{ok:true,recipe} 또는 오류 코드", "planFromYoutube()", "ask() · call()",
  "▷ Gemini REST", "lib/adapter/gemini-recipe-gateway.ts :: fromYoutube() :F20",
  "lib/adapter/gemini-recipe-gateway.ts:F20"),
 ("FUNC034", "youtubeThumb()", "M3", "FN04", "url",
  "영상 ID 를 추출해 썸네일 URL 을 생성한다. ID 가 없으면 표시하지 않는다",
  "i.ytimg.com URL 또는 null", "components/shop/youtube-source.tsx",
  "youtubeVideoId()", "없음", "lib/domain/recipe.ts :: youtubeThumb() :F30",
  "lib/domain/recipe.ts:F30"),
 ("FUNC035", "youtubeVideoId()", "M3", "FN04", "url",
  "URL 에서 11자 영상 ID 를 추출한다", "ID 문자열 또는 null", "youtubeThumb()", "없음",
  "없음", "lib/domain/recipe.ts :: youtubeVideoId() :F28", "lib/domain/recipe.ts:F28"),

 # ── FN05 냉장고 재료 레시피 생성 ────────────────────────
 ("FUNC036", "findFridgeIdeas()", "M3", "FN05", "raw, servings, gateway",
  "보유 재료를 파싱해 요리 후보를 요청한다. 이 단계에서는 저장하지 않는다",
  "{ok:true,ideas} 또는 오류 코드", "run()",
  "readFridgeItems() · gateway.fridgeIdeas()", "없음",
  "lib/usecase/plan-recipe.ts :: findFridgeIdeas() :F12", "lib/usecase/plan-recipe.ts:F12"),
 ("FUNC037", "planFromFridgeIdea()", "M3", "FN05", "dish, raw, servings, gateway, store",
  "보유 재료를 다시 파싱해 선택한 요리명과 함께 전달하고 레시피를 기록한다",
  "{ok:true,recipe} 또는 오류 코드", "components/pick/pick-cards.tsx:F13",
  "readFridgeItems() · gateway.fromFridgeDish() · finish()", "없음",
  "lib/usecase/plan-recipe.ts :: planFromFridgeIdea() :F13",
  "lib/usecase/plan-recipe.ts:F13"),
 ("FUNC038", "readFridgeItems()", "M3", "FN05", "raw: string",
  "재료를 분리 · 정규화해 최대 20개로 만들고 2개 미만이면 거절한다",
  "{ok:true,items} 또는 'empty'|'too-few'",
  "findFridgeIdeas() · planFromFridgeIdea()", "없음", "없음",
  "lib/domain/recipe.ts :: readFridgeItems() :F32", "lib/domain/recipe.ts:F32"),
 ("FUNC039", "readFridgeIdeas()", "M3", "FN05", "value: unknown",
  "후보 항목별 title 을 검증하고 무효 항목을 제외해 5개까지 수집한다", "FridgeIdea[]",
  "fridgeIdeas()", "없음", "없음",
  "lib/domain/recipe.ts :: readFridgeIdeas() :F37", "lib/domain/recipe.ts:F37"),
 ("FUNC040", "fridgeIdeas()", "M3", "FN05", "items, servings",
  "IDEAS_SCHEMA 로 후보 목록을 요청하고 0개면 거절한다", "{ok:true,ideas} 또는 'no-idea'",
  "findFridgeIdeas()", "call() · readFridgeIdeas()", "▷ Gemini REST",
  "lib/adapter/gemini-recipe-gateway.ts :: fridgeIdeas() :F21",
  "lib/adapter/gemini-recipe-gateway.ts:F21"),

 # ── FN06 음성 기반 요리 진행 ────────────────────────────
 ("FUNC041", "start()", "M4", "FN06", "없음 (/cook 진입)",
  "API Key 를 확인하고 마이크 · 스피커를 연 뒤 실시간 음성 세션을 연결한다", "없음",
  "/cook 진입 시 자동", "findSavedKey() · openMic() · openSpeaker() · geminiLiveGateway()",
  "▷ 마이크 · 스피커", "components/cook/live-console.tsx :: start() :F12",
  "components/cook/live-console.tsx:F12"),
 ("FUNC042", "geminiLiveGateway()", "M4", "FN06", "apiKey",
  "WebSocket 을 열고 음성 모델 · 시스템 지시문 · 전사 설정을 전달한 뒤 조각을 주고받는다",
  "LiveVoiceGateway (open · send · say · close)", "start()",
  "cookingBrief() · session.send() · session.say()", "▷ Gemini WebSocket",
  "lib/adapter/gemini-live-gateway.ts :: geminiLiveGateway() :F1",
  "lib/adapter/gemini-live-gateway.ts:F1"),
 ("FUNC043", "cookingBrief()", "M4", "FN06", "brief (레시피 · 조리 단계)",
  "세션 시작 시 1회 전달하는 시스템 지시문을 생성한다", "지시문 문자열",
  "geminiLiveGateway()", "없음", "없음",
  "lib/usecase/cook-along.ts :: cookingBrief() :F1", "lib/usecase/cook-along.ts:F1"),
 ("FUNC044", "handleHeard()", "M4", "FN06", "text (전사된 발화)",
  "발화에서 단계 명령과 타이머 요청을 각각 판정해 화면과 타이머에 전달한다", "없음",
  "WebSocket 전사 이벤트", "readStepCommand() · readTimerRequest()", "없음",
  "components/cook/live-console.tsx :: handleHeard() :F8",
  "components/cook/live-console.tsx:F8"),
 ("FUNC045", "readStepCommand()", "M4", "FN06", "text",
  "의문형이면 판정하지 않고, 접사를 제거해 8자 이내 토큰만 명령어와 대조한다",
  "'next'|'prev'|'repeat' 또는 null", "handleHeard()", "없음", "없음",
  "lib/domain/cook-progress.ts :: readStepCommand() :F20",
  "lib/domain/cook-progress.ts:F20"),
 ("FUNC046", "readTimerRequest()", "M4", "FN06", "text",
  "타이머 키워드가 있을 때만 시 · 분을 추출해 1~1440 범위를 검사한다",
  "분(number) 또는 null", "handleHeard()", "없음", "없음",
  "lib/domain/cook-progress.ts :: readTimerRequest() :F10",
  "lib/domain/cook-progress.ts:F10"),
 ("FUNC047", "moveStep()", "M4", "FN06", "now, by, total",
  "조리 단계 번호를 범위 내로 보정한다", "number", "cook-shell onCommand", "없음", "없음",
  "lib/domain/cook-progress.ts :: moveStep() :F1", "lib/domain/cook-progress.ts:F1"),
 ("FUNC048", "readStepNote()", "M4", "FN06", "index, total, text",
  "해당 조리 단계 낭독 지시문을 만든다", "지시문 문자열", "cook-shell readAloud()",
  "없음", "없음", "lib/usecase/cook-along.ts :: readStepNote() :F6",
  "lib/usecase/cook-along.ts:F6"),
 ("FUNC049", "spokenStep()", "M4", "FN06", "text",
  "낭독용 문자열만 추출한다. 모델 지시문과 분리한다", "낭독 문자열",
  "cook-shell readAloud()", "없음", "없음",
  "lib/usecase/cook-along.ts :: spokenStep() :F5", "lib/usecase/cook-along.ts:F5"),
 ("FUNC050", "readAloud()", "M4", "FN06", "없음 (스피커 버튼)",
  "세션 · 임시 세션 · 브라우저 음성 합성 3순위로 조리 단계를 낭독한다", "없음",
  "사용자 이벤트 (스피커)",
  "readStepNote() · spokenStep() · session.say() · previewVoice() · speakWithBrowser()",
  "없음", "components/cook/cook-shell.tsx :: readAloud() :F14",
  "components/cook/cook-shell.tsx:F14"),
 ("FUNC051", "previewVoice()", "M4", "FN06",
  "apiKey, gender, tone, line, onAudio, onDone",
  "임시 WebSocket 을 열어 한 문장만 낭독하고 종료한다. 실패하면 3순위로 넘긴다",
  "해제 함수", "readAloud()", "없음", "▷ Gemini WebSocket",
  "lib/adapter/gemini-live-gateway.ts :: previewVoice() :F19",
  "lib/adapter/gemini-live-gateway.ts:F19"),
 ("FUNC052", "speakWithBrowser()", "M4", "FN06", "text, gender, tone, onDone",
  "한국어 음성을 선택하고 말투별 rate · pitch 를 적용해 출력한다", "없음",
  "readAloud()", "pickVoice()", "▷ speechSynthesis",
  "lib/adapter/browser-speech.ts :: speakWithBrowser() :F8",
  "lib/adapter/browser-speech.ts:F8"),
 ("FUNC053", "pickVoice()", "M4", "FN06", "gender",
  "한국어 음성만 걸러 성별 힌트 이름을 대조하고, 없으면 반대 성별을 제외해 선택한다",
  "SpeechSynthesisVoice 또는 null", "speakWithBrowser()", "없음", "▷ speechSynthesis",
  "lib/adapter/browser-speech.ts :: pickVoice() :F2", "lib/adapter/browser-speech.ts:F2"),
 ("FUNC054", "keepCookSetup()", "M4", "FN06", "setup, store",
  "선택한 음성 성별 · 말투 · 응답 속도를 기록한다", "boolean",
  "components/setup/setup-picker.tsx:F15", "store.save()", "▷ localStorage",
  "lib/usecase/choose-cook-setup.ts :: keepCookSetup() :F1",
  "lib/usecase/choose-cook-setup.ts:F1"),
 ("FUNC055", "findCookSetup()", "M4", "FN06", "store",
  "기록된 음성 설정을 조회한다", "CookSetup", "cook-shell · pick-shell · home-me",
  "store.load()", "▷ localStorage",
  "lib/usecase/choose-cook-setup.ts :: findCookSetup() :F4",
  "lib/usecase/choose-cook-setup.ts:F4"),

 # ── FN07 게시글 작성 · 수정 · 삭제 ──────────────────────
 ("FUNC056", "publishPostAction()", "M5", "FN07", "prev, formData",
  "게시 유스케이스를 호출하고 성공 시 목록 캐시를 무효화한 뒤 글 화면으로 이동시킨다",
  "WriteFormState 또는 redirect('/posts/<id>')", "components/write/write-form.tsx",
  "writePost() · revalidatePath() · redirect()", "없음",
  "app/actions/post.ts :: publishPostAction() :F2", "app/actions/post.ts:F2"),
 ("FUNC057", "writePost()", "M5", "FN07", "raw, gateway",
  "초안을 검증하고 통과 시 게시글을 등록한다", "{ok:true,id} 또는 오류 코드",
  "publishPostAction()", "readPostDraft() · supabasePostGateway.publish()", "없음",
  "lib/usecase/write-post.ts :: writePost() :F1", "lib/usecase/write-post.ts:F1"),
 ("FUNC058", "readPostDraft()", "M5", "FN07",
  "제목 · 요약 · 본문 · 카테고리 · 소요 시간 · 이미지 URL",
  "길이 검증 6종을 거치고 자체 버킷이 아닌 이미지 URL 은 제거한다",
  "{ok:true,draft} 또는 problem", "writePost() · revisePost()", "없음", "없음",
  "lib/domain/post-draft.ts :: readPostDraft() :F3", "lib/domain/post-draft.ts:F3"),
 ("FUNC059", "draftFromRecipe()", "M5", "FN07", "recipe, tone",
  "레시피를 본문 · 태그 · 소요 시간으로 변환해 폼 초기값을 만든다", "PostDraft",
  "components/write/write-form.tsx:F10", "없음", "없음",
  "lib/domain/recipe-to-post.ts :: draftFromRecipe() :F7",
  "lib/domain/recipe-to-post.ts:F7"),
 ("FUNC060", "supabasePostGateway.publish()", "M5", "FN07", "draft",
  "게시글을 등록하고 게시 전환을 호출한다. 전환 실패를 무시하지 않는다",
  "{ok:true,id} 또는 'rejected'", "writePost()", "없음", "▷ Supabase (posts · RPC)",
  "lib/adapter/supabase-post-gateway.ts :: publish() :F3",
  "lib/adapter/supabase-post-gateway.ts:F3"),
 ("FUNC061", "uploadCover()", "M5", "FN07", "png: Blob",
  "인증 사용자 ID 로 경로를 만들어 표지 이미지를 업로드하고 공개 URL 을 받는다",
  "{ok:true,url} 또는 오류 코드", "components/write/write-form.tsx:F14", "없음",
  "▷ Supabase Storage (post-covers)",
  "lib/adapter/browser-cover-upload.ts :: uploadCover() :F3",
  "lib/adapter/browser-cover-upload.ts:F3"),
 ("FUNC062", "drawRecipeCard()", "M5", "FN07", "canvas, recipe, tone",
  "표지 이미지를 Canvas 에 렌더링한다", "없음",
  "components/write/write-form.tsx:F12 · components/cook/done-shell.tsx:F10", "없음",
  "없음", "lib/recipe-card.ts :: drawRecipeCard() :F1", "lib/recipe-card.ts:F1"),
 ("FUNC063", "revisePostAction()", "M5", "FN07", "prev, formData",
  "수정 유스케이스를 호출하고 성공 시 글 화면으로 이동시킨다",
  "WriteFormState 또는 redirect", "components/write/write-form.tsx", "revisePost()",
  "없음", "app/actions/post.ts :: revisePostAction() :F10", "app/actions/post.ts:F10"),
 ("FUNC064", "revisePost()", "M5", "FN07", "id, raw, gateway",
  "작성과 동일한 검증을 거쳐 수정하고 영향 행 0이면 타 사용자 게시글로 판정한다",
  "{ok:true} 또는 'rejected'", "revisePostAction()",
  "readPostDraft() · supabasePostGateway.revise()", "없음",
  "lib/usecase/write-post.ts :: revisePost() :F6", "lib/usecase/write-post.ts:F6"),
 ("FUNC065", "removePostAction()", "M5", "FN07", "id",
  "삭제 유스케이스를 호출하고 목록으로 이동시킨다", "redirect('/community')",
  "components/post/post-actions.tsx:F11", "removePost()", "없음",
  "app/actions/post.ts :: removePostAction() :F14", "app/actions/post.ts:F14"),
 ("FUNC066", "removePost()", "M5", "FN07", "id, gateway",
  "게시글을 삭제한다. 댓글 · 좋아요는 on delete cascade 로 함께 삭제된다",
  "{ok:true} 또는 오류 코드", "removePostAction()",
  "supabasePostGateway.remove()", "▷ Supabase (posts)",
  "lib/usecase/write-post.ts :: removePost() :F11", "lib/usecase/write-post.ts:F11"),

 # ── FN08 댓글 ───────────────────────────────────────────
 ("FUNC067", "commentAction()", "M5", "FN08", "prev, formData",
  "댓글 작성 유스케이스를 호출하고 시도 번호를 늘려 입력칸을 초기화한다", "TalkFormState",
  "components/post/live-talk.tsx:F2", "writeComment() · revalidatePath()", "없음",
  "app/actions/post.ts :: commentAction() :F17", "app/actions/post.ts:F17"),
 ("FUNC068", "writeComment()", "M5", "FN08", "postId, raw, gateway",
  "본문을 검증하고 통과 시 댓글을 등록한다", "{ok:true} 또는 오류 코드",
  "commentAction()", "checkComment() · supabaseCommentGateway.add()", "없음",
  "lib/usecase/discuss-post.ts :: writeComment() :F11", "lib/usecase/discuss-post.ts:F11"),
 ("FUNC069", "checkComment()", "M5", "FN08", "raw: string",
  "공백 · 2자 미만 · 500자 초과를 검사한다", "{ok:true,text} 또는 problem",
  "writeComment() · reviseComment() · sayOnPost()", "없음", "없음",
  "lib/domain/post.ts :: checkComment() :F2", "lib/domain/post.ts:F2"),
 ("FUNC070", "postComments()", "M5", "FN08", "postId, postAuthorId",
  "작성 시각 오름차순으로 조회하고 mine · canRemove · edited · 표시 시각을 계산한다",
  "LiveComment[]", "app/posts/[id]/page.tsx", "readAvatarUrl() · whenText()",
  "▷ Supabase (post_comments)",
  "lib/adapter/supabase-post-reader.ts :: postComments() :F14",
  "lib/adapter/supabase-post-reader.ts:F14"),
 ("FUNC071", "reviseComment()", "M5", "FN08", "commentId, raw, gateway",
  "작성과 동일한 검증을 거쳐 수정하고 영향 행 0이면 타 사용자 댓글로 판정한다",
  "{ok:true} 또는 'rejected'", "app/actions/post.ts:F21",
  "checkComment() · supabaseCommentGateway.edit()", "없음",
  "lib/usecase/discuss-post.ts :: reviseComment() :F15",
  "lib/usecase/discuss-post.ts:F15"),
 ("FUNC072", "dropComment()", "M5", "FN08", "commentId, gateway",
  "댓글을 삭제한다. 삭제 권한은 RLS 정책이 판정한다", "{ok:true} 또는 오류 코드",
  "app/actions/post.ts:F23", "supabaseCommentGateway.remove()",
  "▷ Supabase (post_comments)",
  "lib/usecase/discuss-post.ts :: dropComment() :F19", "lib/usecase/discuss-post.ts:F19"),
 ("FUNC073", "sayOnPost()", "M5", "FN08", "store, postId, raw, who",
  "예시 게시글의 댓글을 브라우저에 기록한다", "{ok:true} 또는 오류 코드",
  "components/post/post-talk.tsx:F5", "checkComment() · store.save()",
  "▷ localStorage 'cookpilot.comments'",
  "lib/usecase/discuss-post.ts :: sayOnPost() :F1", "lib/usecase/discuss-post.ts:F1"),
 ("FUNC074", "findMyComments()", "M5", "FN08", "store, postId",
  "그 게시글에 기록한 브라우저 댓글을 조회한다", "LocalComment[]",
  "components/post/post-talk.tsx:F3", "store.load()", "▷ localStorage",
  "lib/usecase/discuss-post.ts :: findMyComments() :F9",
  "lib/usecase/discuss-post.ts:F9"),

 # ── FN09 좋아요 · 즐겨찾기 ──────────────────────────────
 ("FUNC075", "likeAction()", "M5", "FN09", "postId, on",
  "좋아요 유스케이스를 호출하고 목록 · 글 화면 캐시를 무효화한다",
  "{ok} — 실패 시 화면 상태 원복", "components/post/post-actions.tsx:F4",
  "toggleLike() · revalidatePath()", "없음",
  "app/actions/post.ts :: likeAction() :F25", "app/actions/post.ts:F25"),
 ("FUNC076", "toggleLike()", "M5", "FN09", "postId, on(화면이 계산한 다음 상태), gateway",
  "uuid 가 아닌 예시 게시글을 제외한 뒤 상태를 반영한다", "{ok:true,on} 또는 'rejected'",
  "likeAction()", "looksLikePost() · gateway.setLike()", "없음",
  "lib/usecase/react-to-post.ts :: toggleLike() :F2", "lib/usecase/react-to-post.ts:F2"),
 ("FUNC077", "looksLikePost()", "M5", "FN09", "postId",
  "게시글 ID 가 uuid 형식인지 판정한다", "boolean", "toggleLike() · toggleBookmark()",
  "없음", "없음", "lib/usecase/react-to-post.ts :: looksLikePost() :F1",
  "lib/usecase/react-to-post.ts:F1"),
 ("FUNC078", "toggleBookmark()", "M5", "FN09", "postId, on, gateway",
  "즐겨찾기 상태를 반영한다. 집계하지 않으며 타 사용자에게 노출되지 않는다",
  "{ok:true,on} 또는 'rejected'", "app/actions/post.ts:F27",
  "looksLikePost() · gateway.setBookmark()", "없음",
  "lib/usecase/react-to-post.ts :: toggleBookmark() :F5",
  "lib/usecase/react-to-post.ts:F5"),
 ("FUNC079", "supabaseReactionGateway.set()", "M5", "FN09", "테이블 이름, postId, on",
  "상태에 따라 등록 또는 삭제한다. 중복 키(23505)는 성공으로 처리한다",
  "{ok:true} 또는 오류 코드", "toggleLike() · toggleBookmark()", "없음",
  "▷ Supabase (post_likes · post_bookmarks)",
  "lib/adapter/supabase-reaction-gateway.ts :: set() :F1",
  "lib/adapter/supabase-reaction-gateway.ts:F1"),
 ("FUNC080", "myReactions()", "M5", "FN09", "postId",
  "좋아요와 즐겨찾기 상태를 병렬로 조회한다", "{liked, saved}",
  "app/posts/[id]/page.tsx:F9", "없음",
  "▷ Supabase (post_likes · post_bookmarks)",
  "lib/adapter/supabase-reaction-gateway.ts :: myReactions() :F6",
  "lib/adapter/supabase-reaction-gateway.ts:F6"),

 # ── FN10 프로필 관리 ────────────────────────────────────
 ("FUNC081", "renameAction()", "M2", "FN10", "prev, formData",
  "표시 이름 변경 유스케이스를 호출하고 캐시를 무효화한다", "RenameFormState",
  "components/write/account-form.tsx", "renameMe() · revalidatePath()", "없음",
  "app/actions/post.ts :: renameAction() :F7", "app/actions/post.ts:F7"),
 ("FUNC082", "renameMe()", "M2", "FN10", "raw, gateway",
  "회원가입과 동일한 규칙으로 검증하고 프로필을 갱신한다",
  "{ok:true,name} 또는 오류 코드", "renameAction()",
  "checkDisplayName() · gateway.rename()", "없음",
  "lib/usecase/rename-me.ts :: renameMe() :F1", "lib/usecase/rename-me.ts:F1"),
 ("FUNC083", "setPhotoAction()", "M2", "FN10", "prev, formData",
  "프로필 이미지 URL 변경 유스케이스를 호출하고 캐시를 무효화한다", "PhotoFormState",
  "components/write/photo-form.tsx", "changeMyPhoto() · revalidatePath()", "없음",
  "app/actions/post.ts :: setPhotoAction() :F29", "app/actions/post.ts:F29"),
 ("FUNC084", "changeMyPhoto()", "M2", "FN10", "raw(이미지 URL), gateway",
  "공백이면 이미지를 제거하고, 값이 있으면 자체 버킷 경로인지 검증 후 갱신한다",
  "{ok:true} 또는 'bad-url'", "setPhotoAction()",
  "readAvatarUrl() · gateway.setAvatar()", "없음",
  "lib/usecase/rename-me.ts :: changeMyPhoto() :F6", "lib/usecase/rename-me.ts:F6"),
 ("FUNC085", "readAvatarUrl()", "M2", "FN10", "raw: unknown",
  "https 로 시작하고 '/avatars/' 를 포함하는 URL 만 통과시킨다", "url 또는 null",
  "changeMyPhoto() · supabase-post-reader", "없음", "없음",
  "lib/domain/avatar.ts :: readAvatarUrl() :F1", "lib/domain/avatar.ts:F1"),
 ("FUNC086", "avatarLetter()", "M2", "FN10", "name",
  "이미지가 없을 때 표시할 첫 글자를 만든다", "문자 1개", "화면 아바타 컴포넌트", "없음",
  "없음", "lib/domain/avatar.ts :: avatarLetter() :F7", "lib/domain/avatar.ts:F7"),
 ("FUNC087", "uploadAvatar()", "M2", "FN10", "file: File",
  "중앙 정사각형으로 잘라 256px webp 로 변환한 뒤 업로드하고 공개 URL 을 받는다",
  "{ok:true,url} 또는 'not-image'", "components/write/photo-form.tsx:F5", "shrink()",
  "▷ Supabase Storage (avatars)",
  "lib/adapter/browser-avatar-upload.ts :: uploadAvatar() :F6",
  "lib/adapter/browser-avatar-upload.ts:F6"),

 # ── FN11 AI 요리 상담 ───────────────────────────────────
 ("FUNC088", "POST()", "M6", "FN11", "request (질문 · 대화 이력 · 브라우저 보관 Key)",
  "Key 를 검증하고 RAG 체인을 구성해 상담 유스케이스를 호출한다",
  "JSON {turn, chatId} 또는 오류 코드", "components/ask/ask-shell.tsx:F8",
  "checkApiKey() · langchainRag() · askKitchen()", "없음",
  "app/api/chat/route.ts :: POST() :F4", "app/api/chat/route.ts:F4"),
 ("FUNC089", "askKitchen()", "M6", "FN11", "raw, history, chain, log, chatId",
  "질문을 검증하고 대화 세션을 확보한 뒤 질문을 먼저 기록하고 검색 · 응답을 수행한다",
  "{ok:true,turn,chatId} 또는 오류 코드", "POST()",
  "checkQuestion() · recentTurns() · chain.run() · log.add()", "없음",
  "lib/usecase/ask-kitchen.ts :: askKitchen() :F1", "lib/usecase/ask-kitchen.ts:F1"),
 ("FUNC090", "checkQuestion()", "M6", "FN11", "raw: string",
  "공백 · 2자 미만 · 500자 초과를 검사한다", "{ok:true,text} 또는 problem",
  "askKitchen()", "없음", "없음", "lib/domain/ask.ts :: checkQuestion() :F1",
  "lib/domain/ask.ts:F1"),
 ("FUNC091", "recentTurns()", "M6", "FN11", "history",
  "최근 6턴만 유지한다. 전량 전송 시 프롬프트 한도를 초과한다", "ChatTurn[]",
  "askKitchen()", "없음", "없음", "lib/domain/ask.ts :: recentTurns() :F5",
  "lib/domain/ask.ts:F5"),
 ("FUNC092", "foldSources()", "M6", "FN11", "refs",
  "동일 dishId 의 출처를 중복 제거한다", "SourceRef[]", "run()", "없음", "없음",
  "lib/domain/ask.ts :: foldSources() :F7", "lib/domain/ask.ts:F7"),
 ("FUNC093", "run()", "M6", "FN11", "question, 최근 대화 턴",
  "유사 후기를 검색하고 그 결과로 응답을 생성한다. 검색 0건 · 본문 공백은 거절한다",
  "{ok:true,text,sources} 또는 'key'|'no-hits'", "askKitchen()",
  "retriever.invoke() · chain.invoke() · foldSources()", "▷ Pinecone · Gemini",
  "lib/adapter/langchain-rag.ts :: run() :F22", "lib/adapter/langchain-rag.ts:F22"),
 ("FUNC094", "supabaseChatLog.open()", "M6", "FN11", "title",
  "새 대화 세션을 생성한다", "chatId", "askKitchen()", "없음", "▷ Supabase (chats)",
  "lib/adapter/supabase-chat-log.ts :: open() :F5", "lib/adapter/supabase-chat-log.ts:F5"),
 ("FUNC095", "supabaseChatLog.add()", "M6", "FN11", "chatId, turn",
  "대화 메시지를 기록한다. 질문은 응답 실패와 무관하게 먼저 기록한다", "없음",
  "askKitchen()", "없음", "▷ Supabase (messages)",
  "lib/adapter/supabase-chat-log.ts :: add() :F6", "lib/adapter/supabase-chat-log.ts:F6"),
 ("FUNC096", "supabaseChatLog.read()", "M6", "FN11", "chatId",
  "테이블을 직접 조회하지 않고 RPC 함수로 대화 메시지를 읽는다", "ChatTurn[]",
  "app/api/chat/[id]/route.ts:F3", "없음", "▷ Supabase (rpc chat_messages)",
  "lib/adapter/supabase-chat-log.ts :: read() :F7", "lib/adapter/supabase-chat-log.ts:F7"),
 ("FUNC097", "findChatId()", "M6", "FN11", "store",
  "이어 붙일 대화 ID 를 조회한다", "chatId 또는 null", "components/ask/ask-shell.tsx",
  "store.load()", "▷ localStorage 'cookpilot.chat-id'",
  "lib/usecase/ask-kitchen.ts :: findChatId() :F12", "lib/usecase/ask-kitchen.ts:F12"),
 ("FUNC098", "keepChatId()", "M6", "FN11", "store, id",
  "새로 열린 대화 ID 를 기록한다", "없음", "components/ask/ask-shell.tsx",
  "store.save()", "▷ localStorage",
  "lib/usecase/ask-kitchen.ts :: keepChatId() :F13", "lib/usecase/ask-kitchen.ts:F13"),
 ("FUNC099", "forgetChatId()", "M6", "FN11", "store",
  "대화 ID 를 삭제해 다음 질문이 새 대화로 열리게 한다", "없음",
  "components/ask/ask-shell.tsx:F18", "store.clear()", "▷ localStorage",
  "lib/usecase/ask-kitchen.ts :: forgetChatId() :F14", "lib/usecase/ask-kitchen.ts:F14"),
 ("FUNC100", "indexReviews()", "M6", "FN11", "reviews",
  "후기별 검색 대상 문자열로 Document 를 만들고 80건 단위로 나눠 업로드한다",
  "{ok:true,count}", "app/api/kitchen/index/route.ts:F1",
  "reviewText() · store.addDocuments()", "▷ Pinecone",
  "lib/adapter/langchain-rag.ts :: indexReviews() :F10",
  "lib/adapter/langchain-rag.ts:F10"),
 ("FUNC101", "loadReviews()", "M6", "FN11", "없음",
  "후기 CSV 를 읽어 행별로 변환하고 무효 행은 건너뛴다", "{reviews, skipped}",
  "app/api/kitchen/index/route.ts:F1", "readReviewRow()", "▷ 파일 samples/reviews.csv",
  "lib/adapter/csv-reviews.ts :: loadReviews() :F4", "lib/adapter/csv-reviews.ts:F4"),
 ("FUNC102", "readReviewRow()", "M6", "FN11", "row",
  "id · content · dish 가 비면 그 행을 제외한다", "Review 또는 null", "loadReviews()",
  "없음", "없음", "lib/domain/review.ts :: readReviewRow() :F3",
  "lib/domain/review.ts:F3"),
 ("FUNC103", "reviewText()", "M6", "FN11", "review",
  "후기 1건을 검색 대상 문자열로 변환한다. 이 문자열이 벡터가 된다", "문자열",
  "indexReviews()", "없음", "없음", "lib/domain/review.ts :: reviewText() :F9",
  "lib/domain/review.ts:F9"),
 ("FUNC104", "searchOnly()", "M6", "FN11", "question, take",
  "업로드 없이 검색 결과 건수만 확인한다. 운영 점검용이다", "검색 결과",
  "app/api/kitchen/index/route.ts:F6", "없음", "▷ Pinecone",
  "lib/adapter/langchain-rag.ts :: searchOnly() :F17",
  "lib/adapter/langchain-rag.ts:F17"),

 # ── FN12 저장 레시피 관리 ───────────────────────────────
 ("FUNC105", "shelveRecipe()", "M7", "FN12", "book, store",
  "동일 제목 항목을 제외하고 선두에 추가한다", "{ok:true,count}",
  "components/cook/done-shell.tsx:F8", "findShelfBooks() · store.replace()",
  "▷ localStorage 'cookpilot.recipe-shelf'",
  "lib/usecase/keep-recipe-shelf.ts :: shelveRecipe() :F7",
  "lib/usecase/keep-recipe-shelf.ts:F7"),
 ("FUNC106", "findShelfBooks()", "M7", "FN12", "store",
  "저장된 레시피 항목 전체를 조회한다", "ShelfBook[]",
  "shelf-stand · shelveRecipe() · unshelveBook()", "store.load()", "▷ localStorage",
  "lib/usecase/keep-recipe-shelf.ts :: findShelfBooks() :F2",
  "lib/usecase/keep-recipe-shelf.ts:F2"),
 ("FUNC107", "unshelveBook()", "M7", "FN12", "id, store",
  "해당 ID 항목을 제외하고 다시 기록한다", "{ok:true,count}",
  "components/shelf/shelf-stand.tsx:F10", "store.replace()", "▷ localStorage",
  "lib/usecase/keep-recipe-shelf.ts :: unshelveBook() :F12",
  "lib/usecase/keep-recipe-shelf.ts:F12"),
 ("FUNC108", "cookAgain()", "M7", "FN12", "recipe",
  "Recipe 구조를 검증해 출처를 'shelf' 로 지정한 임시 레시피로 기록하고 이동시킨다",
  "없음 (/shop 이동)", "사용자 이벤트 (표지 클릭)",
  "readRecipe() · browserRecipeDraftStore.save()", "▷ localStorage",
  "components/shelf/shelf-stand.tsx :: cookAgain() :F6",
  "components/shelf/shelf-stand.tsx:F6"),
 ("FUNC109", "makeShelfBackup()", "M7", "FN12", "store",
  "저장 항목을 백업 문자열로 만든다", "JSON 문자열", "shelf-stand · pick-rail",
  "findShelfBooks() · writeBackup()", "▷ localStorage",
  "lib/usecase/keep-recipe-shelf.ts :: makeShelfBackup() :F5",
  "lib/usecase/keep-recipe-shelf.ts:F5"),
 ("FUNC110", "writeBackup()", "M7", "FN12", "books",
  "버전을 포함해 JSON 문자열로 직렬화한다", "문자열", "makeShelfBackup()", "없음", "없음",
  "lib/domain/recipe-shelf.ts :: writeBackup() :F2", "lib/domain/recipe-shelf.ts:F2"),
 ("FUNC111", "restoreShelfBackup()", "M7", "FN12", "text, store",
  "검증에 실패하면 기존 저장 항목을 변경하지 않는다", "{ok:true,count} 또는 오류 코드",
  "shelf-stand · pick-rail", "readBackup() · store.replace()", "▷ localStorage",
  "lib/usecase/keep-recipe-shelf.ts :: restoreShelfBackup() :F16",
  "lib/usecase/keep-recipe-shelf.ts:F16"),
 ("FUNC112", "readBackup()", "M7", "FN12", "text",
  "JSON 형식 · 버전 · 항목 구조를 검사하고 하나라도 불일치하면 전체를 거절한다",
  "{ok:true,books} 또는 'broken'|'version'|'shape'", "restoreShelfBackup()", "없음",
  "없음", "lib/domain/recipe-shelf.ts :: readBackup() :F5",
  "lib/domain/recipe-shelf.ts:F5"),
 ("FUNC113", "emptyShelf()", "M7", "FN12", "store",
  "저장 항목 전체를 삭제한다", "없음", "components/pick/pick-rail.tsx:F12",
  "store.replace()", "▷ localStorage",
  "lib/usecase/keep-recipe-shelf.ts :: emptyShelf() :F4",
  "lib/usecase/keep-recipe-shelf.ts:F4"),

 # ── FN13 커뮤니티 목록 · 검색 · 태그 ────────────────────
 ("FUNC114", "CommunityPage()", "M5", "FN13", "searchParams(tab · q)",
  "탭과 검색어를 정규화하고 목록을 조회해 필터링한다", "화면(JSX)", "라우트 진입",
  "resolveTab() · resolveQuery() · livePosts() · matchesQuery()", "없음",
  "app/community/page.tsx :: CommunityPage() :F1", "app/community/page.tsx:F1"),
 ("FUNC115", "resolveTab()", "M5", "FN13", "raw: string|string[]|undefined",
  "배열이면 마지막 값을 쓰고 미등록 값이면 기본 탭으로 정리한다", "CommunityTab",
  "CommunityPage()", "없음", "없음",
  "lib/domain/community-tab.ts :: resolveTab() :F1", "lib/domain/community-tab.ts:F1"),
 ("FUNC116", "resolveQuery()", "M5", "FN13", "raw: string|string[]|undefined",
  "공백을 제거하고 60자로 자른다", "검색어 문자열", "CommunityPage()", "없음", "없음",
  "lib/domain/community-tab.ts :: resolveQuery() :F5", "lib/domain/community-tab.ts:F5"),
 ("FUNC117", "matchesQuery()", "M5", "FN13", "fields(제목 · 작성자 · 태그 · 요약), query",
  "공백 제거와 소문자 변환 후 한 필드라도 일치하면 통과시킨다", "boolean",
  "CommunityPage()", "없음", "없음",
  "lib/domain/community-tab.ts :: matchesQuery() :F8", "lib/domain/community-tab.ts:F8"),
 ("FUNC118", "livePosts()", "M5", "FN13", "limit",
  "게시글과 프로필을 조인해 최신순으로 조회하고 컬럼 미존재 오류 시 재조회한다",
  "LivePost[] (실패하면 빈 배열)", "CommunityPage()", "readRow() · readAvatarUrl()",
  "▷ Supabase (posts · profiles)",
  "lib/adapter/supabase-post-reader.ts :: livePosts() :F6",
  "lib/adapter/supabase-post-reader.ts:F6"),
 ("FUNC119", "livePost()", "M5", "FN13", "id",
  "게시글 1건을 조회한다", "LivePost 또는 null", "app/posts/[id]/page.tsx", "readRow()",
  "▷ Supabase (posts)", "lib/adapter/supabase-post-reader.ts :: livePost() :F11",
  "lib/adapter/supabase-post-reader.ts:F11"),
 ("FUNC120", "photoPath()", "M5", "FN13", "postId",
  "예시 게시글 이미지 경로를 규칙으로 생성한다", "경로 문자열",
  "CommunityPage() · post-article", "없음", "없음",
  "lib/domain/post.ts :: photoPath() :F1", "lib/domain/post.ts:F1"),
 ("FUNC121", "findPostDetail()", "M5", "FN13", "all, id",
  "예시 게시글 16건 중 하나를 ID 로 찾는다", "PostDetail 또는 null",
  "app/posts/[id]/page.tsx", "없음", "없음",
  "lib/domain/post.ts :: findPostDetail() :F6", "lib/domain/post.ts:F6"),
]
