# -*- coding: utf-8 -*-
"""기능 체크리스트 · 데이터 사전 · 화면 여정."""

# ── 02_기능체크리스트 ────────────────────────────────────
# (체크ID, 모듈ID, 기능ID, 체크항목, 예상동작, 구현상태, 구현위치, 관련함수,
#  테스트필요, 비고, 근거)
CHECKS = [
 ("C1", "M1", "FN01", "API Key 를 입력하고 저장할 수 있는가?",
  "저장 후 '키 저장됨' 상태 카드가 표시된다", "구현됨",
  "lib/usecase/enter-with-api-key.ts :: enterWithApiKey() :F1",
  "onSubmit() · enterWithApiKey()", "예", "",
  "components/start/api-key-form.tsx:F5"),
 ("C2", "M1", "FN01", "공백만 입력하면 저장이 거절되는가?",
  "오류 코드 'empty' 로 현재 화면에 오류 메시지가 표시된다", "구현됨",
  "lib/domain/api-key.ts :: checkApiKey() :F1", "checkApiKey()", "예", "",
  "lib/domain/api-key.ts:F3"),
 ("C3", "M1", "FN01", "저장된 API Key 를 재진입 후에도 사용할 수 있는가?",
  "브라우저를 다시 열어도 조회되어 입력 단계를 건너뛴다", "구현됨",
  "lib/usecase/enter-with-api-key.ts :: findSavedKey() :F7", "findSavedKey()", "예",
  "저장소 키 cookpilot.gemini-key", "lib/usecase/enter-with-api-key.ts:F7"),
 ("C4", "M1", "FN01", "'다른 키로 바꾸기' 로 저장된 Key 를 삭제할 수 있는가?",
  "저장소에서 삭제되고 입력칸이 다시 표시된다", "구현됨",
  "lib/usecase/enter-with-api-key.ts :: forgetSavedKey() :F8", "forgetSavedKey()",
  "예", "", "components/start/api-key-form.tsx:F9"),

 ("C5", "M2", "FN02", "이메일 형식이 아닌 값으로 로그인하면 서버 요청 없이 거절되는가?",
  "오류 코드 'email-shape' 로 현재 화면에 오류 메시지가 표시된다", "구현됨",
  "lib/domain/credentials.ts :: checkCredentials() :F1", "checkCredentials()", "예",
  "검증 실패 시 Supabase 에 요청하지 않는다", "lib/usecase/sign-in.ts:F3"),
 ("C6", "M2", "FN02", "로그인에 성공하면 /start 로 이동하는가?",
  "라우트 캐시 무효화 후 /start 로 이동한다", "구현됨",
  "app/actions/auth.ts :: signInAction() :F2", "signInAction()", "예", "",
  "app/actions/auth.ts:F7"),
 ("C7", "M2", "FN02", "로그인 후 원래 접근하려던 화면으로 돌아가는가?",
  "?next= 값의 화면으로 이동한다", "미구현",
  "app/login/page.tsx", "확인 필요", "예",
  "?next= 는 URL 에 부착되지만 /login 에서 읽는 코드가 없다. 로그인 후 항상 /start 로 이동한다",
  "app/write/page.tsx:F4"),
 ("C8", "M2", "FN02", "가입 시 표시 이름 규칙 위반이 걸러지는가?",
  "오류 코드로 현재 화면에 오류 메시지가 표시된다", "구현됨",
  "lib/domain/display-name.ts :: checkDisplayName() :F1", "checkDisplayName()", "예",
  "", "lib/usecase/sign-up.ts:F2"),
 ("C9", "M2", "FN02", "가입 시 프로필 행이 생성되는가?",
  "auth.users 삽입 트리거가 profiles 행을 만든다", "구현됨",
  "supabase/migrations/20260822120000_create_profiles.sql", "handle_new_user()", "예",
  "마이그레이션 적용 필요", "supabase/migrations/20260822120000_create_profiles.sql"),

 ("C10", "M3", "FN03", "음성이 너무 짧으면 모델을 호출하지 않는가?",
  "오류 코드 'unheard' 로 현재 화면에 오류 메시지가 표시된다", "구현됨",
  "lib/usecase/plan-recipe.ts :: planFromSpeech() :F1", "planFromSpeech()", "예",
  "하한 2000바이트", "lib/usecase/plan-recipe.ts:F2"),
 ("C11", "M3", "FN03", "마이크 권한을 거부하면 사유가 구분되어 표시되는가?",
  "'denied' · 'missing' · 'failed' 중 하나로 구분된다", "구현됨",
  "lib/adapter/browser-audio.ts :: openMic() :F2", "openMic()", "예", "",
  "lib/adapter/browser-audio.ts:F5"),
 ("C12", "M3", "FN03", "생성된 레시피가 장보기 화면으로 전달되는가?",
  "브라우저에 기록된 뒤 /shop 에서 조회된다", "구현됨",
  "lib/usecase/plan-recipe.ts :: finish() :F14", "finish() · findDraft()", "예",
  "저장소 키 cookpilot.recipe-draft", "lib/usecase/plan-recipe.ts:F16"),
 ("C13", "M3", "FN03", "재료나 조리 단계가 비면 레시피가 거절되는가?",
  "'empty-ingredients' 또는 'empty-steps' 로 거절된다", "구현됨",
  "lib/domain/recipe.ts :: readRecipe() :F3", "readRecipe()", "예", "",
  "lib/domain/recipe.ts:F10"),
 ("C14", "M3", "FN04", "YouTube 가 아닌 URL 을 넣으면 모델을 호출하지 않는가?",
  "'not-youtube' 로 거절되고 요청이 발생하지 않는다", "구현됨",
  "lib/domain/recipe.ts :: readYoutubeUrl() :F22", "readYoutubeUrl()", "예", "",
  "lib/usecase/plan-recipe.ts:F10"),
 ("C15", "M3", "FN04", "영상 출처(썸네일 · 제목 · 채널)가 장보기 화면에 표시되는가?",
  "썸네일과 영상 제목 · 채널 · 출처 안내가 표시된다", "구현됨",
  "lib/domain/recipe.ts :: youtubeThumb() :F30", "youtubeThumb() · youtubeVideoId()",
  "예", "영상 ID 를 못 뽑으면 썸네일 영역을 만들지 않는다",
  "components/shop/youtube-source.tsx:F1"),
 ("C16", "M3", "FN05", "재료를 1개만 넣으면 거절되는가?",
  "'too-few' 로 거절된다", "구현됨",
  "lib/domain/recipe.ts :: readFridgeItems() :F32", "readFridgeItems()", "예", "",
  "lib/domain/recipe.ts:F35"),
 ("C17", "M3", "FN05", "후보 단계에서는 아무것도 저장되지 않는가?",
  "후보 카드만 표시되고 임시 레시피는 기록되지 않는다", "구현됨",
  "lib/usecase/plan-recipe.ts :: findFridgeIdeas() :F12", "findFridgeIdeas()", "예",
  "", "lib/usecase/plan-recipe.ts:F12"),
 ("C18", "M3", "FN05", "후보를 선택하면 보유 재료가 함께 전달되는가?",
  "요리명과 보유 재료를 함께 보내 레시피가 생성된다", "구현됨",
  "lib/usecase/plan-recipe.ts :: planFromFridgeIdea() :F13", "planFromFridgeIdea()",
  "예", "", "lib/usecase/plan-recipe.ts:F13"),

 ("C19", "M4", "FN06", "API Key 가 없으면 요리 화면에서 세션 연결을 중단하는가?",
  "현재 화면에 오류 메시지를 표시하고 세션을 열지 않는다", "구현됨",
  "components/cook/live-console.tsx :: start() :F12", "start() · findSavedKey()",
  "예", "", "components/cook/live-console.tsx:F13"),
 ("C20", "M4", "FN06", "'다음' 같은 음성 명령으로 조리 단계가 이동하는가?",
  "'next'|'prev'|'repeat' 로 판정되어 단계가 이동한다", "구현됨",
  "lib/domain/cook-progress.ts :: readStepCommand() :F20", "readStepCommand()", "예",
  "", "lib/domain/cook-progress.ts:F27"),
 ("C21", "M4", "FN06", "질문 문장이 단계 이동 명령으로 오판정되지 않는가?",
  "의문형이 포함되면 명령으로 판정하지 않는다", "구현됨",
  "lib/domain/cook-progress.ts :: readStepCommand() :F20", "readStepCommand()", "예",
  "", "lib/domain/cook-progress.ts:F24"),
 ("C22", "M4", "FN06", "'3분 타이머' 같은 음성으로 타이머가 등록되는가?",
  "시 · 분을 추출해 1~1440 범위면 타이머가 등록된다", "구현됨",
  "lib/domain/cook-progress.ts :: readTimerRequest() :F10", "readTimerRequest()",
  "예", "", "lib/domain/cook-progress.ts:F17"),
 ("C23", "M4", "FN06", "스피커 낭독 음성이 마이크 세션 음성과 일치하는가?",
  "세션 · 임시 세션 · 브라우저 합성 어느 경로든 같은 음성 설정을 사용한다", "구현됨",
  "components/cook/cook-shell.tsx :: readAloud() :F14",
  "readAloud() · previewVoice() · speakWithBrowser()", "예",
  "voiceFor[gender][tone] 표를 공유한다", "lib/adapter/gemini-live-gateway.ts:F19"),
 ("C24", "M4", "FN06", "API Key 없이도 조리 단계 낭독이 되는가?",
  "브라우저 음성 합성으로 낭독된다", "구현됨",
  "lib/adapter/browser-speech.ts :: speakWithBrowser() :F8", "speakWithBrowser()",
  "예", "3순위 대비 경로", "lib/adapter/browser-speech.ts:F13"),

 ("C25", "M5", "FN07", "완료한 레시피로 게시글 폼이 미리 채워지는가?",
  "제목 · 본문 · 태그 · 소요 시간이 채워진다", "구현됨",
  "lib/domain/recipe-to-post.ts :: draftFromRecipe() :F7", "draftFromRecipe()", "예",
  "/write?from=cook 로 진입한 경우", "components/write/write-form.tsx:F10"),
 ("C26", "M5", "FN07", "제목이 비었거나 80자를 넘으면 거절되는가?",
  "'title-empty' 또는 'title-long' 으로 거절된다", "구현됨",
  "lib/domain/post-draft.ts :: readPostDraft() :F3", "readPostDraft()", "예", "",
  "lib/domain/post-draft.ts:F4"),
 ("C27", "M5", "FN07", "게시 전환에 실패하면 성공으로 처리되지 않는가?",
  "'rejected' 로 반환되어 오류 메시지가 표시된다", "구현됨",
  "lib/adapter/supabase-post-gateway.ts :: publish() :F3", "publish()", "예",
  "저장은 되었으나 목록에 안 보이는 행을 막는 조건", "lib/adapter/supabase-post-gateway.ts:F6"),
 ("C28", "M5", "FN07", "타 사용자 게시글을 수정하면 거절되는가?",
  "영향 행 0으로 'rejected' 가 반환된다", "구현됨",
  "lib/usecase/write-post.ts :: revisePost() :F6", "revisePost()", "예",
  "RLS 정책과 영향 행 수 이중 확인", "lib/adapter/supabase-post-gateway.ts:F10"),
 ("C29", "M5", "FN07", "게시글을 삭제하면 댓글 · 좋아요도 함께 삭제되는가?",
  "on delete cascade 로 연관 행이 삭제된다", "구현됨",
  "lib/usecase/write-post.ts :: removePost() :F11", "removePost()", "예",
  "마이그레이션 적용 필요",
  "supabase/migrations/20260824090000_likes_bookmarks_comments_avatars.sql"),
 ("C30", "M5", "FN07", "비로그인 상태로 /write 에 접근하면 로그인 화면으로 이동하는가?",
  "/login?next=/write 로 이동한다", "구현됨", "app/write/page.tsx :: WritePage() :F1",
  "currentUserEmail()", "예", "?next= 는 부착되지만 로그인 후에는 /start 로 간다(C7)",
  "app/write/page.tsx:F4"),

 ("C31", "M5", "FN08", "비로그인 상태에서 댓글 폼이 노출되지 않는가?",
  "폼 대신 로그인 링크가 표시된다", "구현됨",
  "components/post/live-talk.tsx :: LiveTalk() :F1", "LiveTalk()", "예", "",
  "components/post/live-talk.tsx:F1"),
 ("C32", "M5", "FN08", "댓글 작성 성공 시 입력칸이 비워지는가?",
  "시도 번호가 증가해 입력칸이 초기화된다", "구현됨",
  "app/actions/post.ts :: commentAction() :F17", "commentAction()", "예", "",
  "components/post/live-talk.tsx:F5"),
 ("C33", "M5", "FN08", "타 사용자 댓글에 수정 · 삭제 버튼이 노출되지 않는가?",
  "서버가 계산한 mine · canRemove 값에 따라 버튼이 결정된다", "구현됨",
  "lib/adapter/supabase-post-reader.ts :: postComments() :F14", "postComments()",
  "예", "화면이 이름 비교로 판정하지 않는다",
  "lib/adapter/supabase-post-reader.ts:F16"),
 ("C34", "M5", "FN08", "게시글 작성자가 타인의 댓글을 삭제할 수 있는가?",
  "댓글 작성자와 게시글 작성자 모두 삭제할 수 있다", "구현됨",
  "lib/usecase/discuss-post.ts :: dropComment() :F19", "dropComment()", "예",
  "RLS 정책이 판정. 마이그레이션 적용 필요", "lib/adapter/supabase-comment-gateway.ts:F12"),
 ("C35", "M5", "FN08", "예시 게시글의 댓글이 브라우저에만 저장되는가?",
  "테이블이 아니라 저장소에 기록되고 목록이 다시 그려진다", "구현됨",
  "lib/usecase/discuss-post.ts :: sayOnPost() :F1", "sayOnPost() · findMyComments()",
  "예", "저장소 키 cookpilot.comments", "components/post/post-talk.tsx:F5"),

 ("C36", "M5", "FN09", "비로그인 상태에서 좋아요를 누르면 안내가 표시되는가?",
  "요청하지 않고 현재 화면에 오류 메시지를 표시한다", "구현됨",
  "components/post/post-actions.tsx :: onHeart() :F4", "onHeart()", "예", "",
  "components/post/post-actions.tsx:F5"),
 ("C37", "M5", "FN09", "좋아요 요청이 실패하면 화면 상태가 원복되는가?",
  "선반영한 상태와 숫자가 되돌아간다", "구현됨",
  "app/actions/post.ts :: likeAction() :F25", "likeAction() · toggleLike()", "예",
  "", "components/post/post-actions.tsx:F6"),
 ("C38", "M5", "FN09", "같은 게시글에 좋아요를 두 번 눌러도 오류가 나지 않는가?",
  "중복 키(23505)는 성공으로 처리된다", "구현됨",
  "lib/adapter/supabase-reaction-gateway.ts :: set() :F1", "set()", "예", "",
  "lib/adapter/supabase-reaction-gateway.ts:F4"),
 ("C39", "M5", "FN09", "예시 게시글(uuid 아님)에 좋아요를 누르면 거절되는가?",
  "'rejected' 로 반환된다", "구현됨",
  "lib/usecase/react-to-post.ts :: looksLikePost() :F1", "looksLikePost()", "예", "",
  "lib/usecase/react-to-post.ts:F3"),
 ("C40", "M5", "FN09", "좋아요 수가 자동으로 갱신되는가?",
  "테이블 트리거가 posts.like_count 를 ±1 한다", "구현됨",
  "supabase/migrations/20260824090000_likes_bookmarks_comments_avatars.sql",
  "sync_post_like_count()", "예", "마이그레이션 적용 필요",
  "supabase/migrations/20260824090000_likes_bookmarks_comments_avatars.sql"),

 ("C41", "M2", "FN10", "프로필 이미지를 올리면 게시글 · 댓글에 반영되는가?",
  "업로드 후 URL 이 프로필에 기록되고 목록 · 글 화면 캐시가 무효화된다", "구현됨",
  "lib/usecase/rename-me.ts :: changeMyPhoto() :F6", "uploadAvatar() · changeMyPhoto()",
  "예", "마이그레이션 적용 필요", "app/actions/post.ts:F29"),
 ("C42", "M2", "FN10", "외부 도메인 이미지 URL 이 거절되는가?",
  "'bad-url' 로 거절된다", "구현됨", "lib/domain/avatar.ts :: readAvatarUrl() :F1",
  "readAvatarUrl()", "예", "https 시작 + '/avatars/' 포함만 통과",
  "lib/domain/avatar.ts:F5"),
 ("C43", "M2", "FN10", "이미지가 없으면 표시 이름 첫 글자가 표시되는가?",
  "대체 문자가 렌더링된다", "구현됨", "lib/domain/avatar.ts :: avatarLetter() :F7",
  "avatarLetter()", "예", "", "lib/domain/avatar.ts:F7"),
 ("C44", "M2", "FN10", "이미지 파일이 아닌 파일을 올리면 거절되는가?",
  "'not-image' 로 거절된다", "구현됨",
  "lib/adapter/browser-avatar-upload.ts :: uploadAvatar() :F6", "uploadAvatar()",
  "예", "", "lib/adapter/browser-avatar-upload.ts:F4"),

 ("C45", "M6", "FN11", "2자 미만 질문이 거절되는가?",
  "'short' 로 거절되고 모델을 호출하지 않는다", "구현됨",
  "lib/domain/ask.ts :: checkQuestion() :F1", "checkQuestion()", "예", "",
  "lib/domain/ask.ts:F3"),
 ("C46", "M6", "FN11", "응답 생성에 실패해도 질문이 기록되는가?",
  "질문은 응답 결과와 무관하게 먼저 기록된다", "구현됨",
  "lib/usecase/ask-kitchen.ts :: askKitchen() :F1", "askKitchen()", "예", "",
  "lib/usecase/ask-kitchen.ts:F6"),
 ("C47", "M6", "FN11", "검색 결과가 없으면 그렇게 안내되는가?",
  "'no-hits' 로 반환되어 현재 화면에 표시된다", "구현됨",
  "lib/adapter/langchain-rag.ts :: run() :F22", "run()", "예", "",
  "lib/adapter/langchain-rag.ts:F30"),
 ("C48", "M6", "FN11", "같은 요리의 근거 후기가 중복 표시되지 않는가?",
  "동일 dishId 는 하나로 접힌다", "구현됨", "lib/domain/ask.ts :: foldSources() :F7",
  "foldSources()", "예", "", "lib/domain/ask.ts:F7"),
 ("C49", "M6", "FN11", "'대화 비우기' 후 새 대화가 열리는가?",
  "대화 ID 가 삭제되어 다음 질문에서 새 세션이 생성된다", "구현됨",
  "lib/usecase/ask-kitchen.ts :: forgetChatId() :F14", "forgetChatId()", "예",
  "저장소 키 cookpilot.chat-id", "components/ask/ask-shell.tsx:F18"),
 ("C50", "M6", "FN11", "지난 대화 목록을 조회할 수 있는가?",
  "확인 필요", "확인 필요", "확인 필요", "확인 필요", "예",
  "chats 테이블에 기록은 하지만 목록을 조회하는 코드를 찾지 못했다",
  "lib/adapter/supabase-chat-log.ts:F5"),
 ("C51", "M6", "FN11", "후기 색인을 실행하면 등록 건수가 반환되는가?",
  "CSV 를 읽어 80건 단위로 업로드하고 건수를 반환한다", "구현됨",
  "lib/adapter/langchain-rag.ts :: indexReviews() :F10",
  "loadReviews() · indexReviews()", "예",
  "운영 작업. FN11 질의 이전에 1회 실행 필요", "app/api/kitchen/index/route.ts:F1"),

 ("C52", "M7", "FN12", "요리 완료 후 레시피를 저장할 수 있는가?",
  "저장 항목 선두에 추가되고 건수가 반환된다", "구현됨",
  "lib/usecase/keep-recipe-shelf.ts :: shelveRecipe() :F7", "shelveRecipe()", "예",
  "저장소 키 cookpilot.recipe-shelf", "components/cook/done-shell.tsx:F8"),
 ("C53", "M7", "FN12", "같은 제목을 다시 저장하면 항목이 중복되지 않는가?",
  "기존 동일 제목 항목이 제외되고 새 항목이 선두에 온다", "구현됨",
  "lib/usecase/keep-recipe-shelf.ts :: shelveRecipe() :F7", "shelveRecipe()", "예",
  "", "lib/usecase/keep-recipe-shelf.ts:F9"),
 ("C54", "M7", "FN12", "저장 항목을 눌러 다시 요리할 수 있는가?",
  "임시 레시피로 기록되고 /shop 으로 이동한다", "구현됨",
  "components/shelf/shelf-stand.tsx :: cookAgain() :F6", "cookAgain() · readRecipe()",
  "예", "출처가 'shelf' 로 지정된다", "components/shelf/shelf-stand.tsx:F7"),
 ("C55", "M7", "FN12", "레시피가 없는 구버전 항목이 비활성화되는가?",
  "표지가 잠기고 안내 문구가 표시된다", "구현됨",
  "components/shelf/shelf-stand.tsx :: ShelfStand() :F2", "readRecipe()", "예",
  "판정은 F2 의 JSX 안에 있고 개별 F 번호는 없다", "components/shelf/shelf-stand.tsx:F2"),
 ("C56", "M7", "FN12", "깨진 백업 파일을 복원하면 기존 항목이 보존되는가?",
  "'broken' · 'version' · 'shape' 로 거절되고 저장 항목을 변경하지 않는다", "구현됨",
  "lib/usecase/keep-recipe-shelf.ts :: restoreShelfBackup() :F16",
  "restoreShelfBackup() · readBackup()", "예", "",
  "lib/usecase/keep-recipe-shelf.ts:F18"),

 ("C57", "M5", "FN13", "검색어로 제목 · 작성자 · 태그 · 요약을 함께 찾는가?",
  "공백 제거 후 한 필드라도 일치하면 목록에 남는다", "구현됨",
  "lib/domain/community-tab.ts :: matchesQuery() :F8", "matchesQuery()", "예", "",
  "lib/domain/community-tab.ts:F11"),
 ("C58", "M5", "FN13", "태그를 누르면 같은 태그로 검색되는가?",
  "/community?q=<태그> 로 이동해 검색과 같은 경로를 탄다", "구현됨",
  "components/community/tag-link.tsx", "TagLink()", "예",
  "태그는 posts.badge 단일 컬럼이라 게시글당 1개다", "components/community/post-cards.tsx:F1"),
 ("C59", "M5", "FN13", "마이그레이션 미적용 상태에서도 목록이 보이는가?",
  "컬럼 미존재 오류 시 해당 컬럼을 빼고 재조회한다", "구현됨",
  "lib/adapter/supabase-post-reader.ts :: livePosts() :F6", "livePosts()", "예",
  "42703 · PGRST200 처리", "lib/adapter/supabase-post-reader.ts:F8"),
 ("C60", "M5", "FN13", "이미지가 없는 예시 게시글에서 깨진 이미지가 표시되지 않는가?",
  "이미지 경로가 없으면 영역 자체를 만들지 않는다", "구현됨",
  "components/community/post-cards.tsx :: Shot() :F1", "photoPath()", "예", "",
  "components/community/post-cards.tsx:F1"),
 ("C61", "M5", "FN13", "브라우저 뒤로 가기로 이전 목록 상태가 복원되는가?",
  "확인 필요", "확인 필요", "확인 필요", "확인 필요", "예",
  "뒤로 가기를 처리하는 코드를 찾지 못했다", "app/community/page.tsx:F1"),
]

# ── 06_데이터사전 ────────────────────────────────────────
# (데이터ID, 저장소, 키/테이블/버킷, 데이터명, 설명, 값/내용,
#  생성/쓰기 위치, 읽기 위치, 삭제 위치, 관련모듈, 관련기능, 근거)
DATA = [
 ("D1-1", "localStorage", "cookpilot.gemini-key", "Gemini API Key",
  "요리 · 상담 기능이 사용하는 외부 API 인증 값. CookPilot 서버에 저장하지 않는다 "
  "(FN11 은 요청 시에만 경유)",
  "Key 문자열 1건",
  "lib/adapter/browser-api-key-store.ts:F4",
  "lib/usecase/enter-with-api-key.ts:F7",
  "lib/usecase/enter-with-api-key.ts:F8 · components/pick/pick-rail.tsx:F12",
  "M1", "FN01 기록 / FN03 · FN04 · FN05 · FN06 · FN11 · FN13 조회",
  "lib/usecase/enter-with-api-key.ts:F4"),
 ("D1-2", "localStorage", "cookpilot.cook-setup", "음성 설정",
  "음성 성별 · 말투 · 응답 속도", "CookSetup 객체 1건",
  "lib/adapter/browser-cook-setup-store.ts:F3",
  "lib/usecase/choose-cook-setup.ts:F4",
  "lib/usecase/choose-cook-setup.ts:F5 · components/pick/pick-rail.tsx:F12",
  "M4", "기능 목록 외 공통 단계 기록 / FN06 · FN13 조회",
  "lib/usecase/choose-cook-setup.ts:F1"),
 ("D1-3", "localStorage", "cookpilot.recipe-draft", "임시 레시피",
  "진행 중인 레시피 1건. 화면 간 전달 값", "Recipe 객체 1건",
  "lib/adapter/browser-recipe-draft-store.ts:F3",
  "lib/usecase/plan-recipe.ts:F18",
  "lib/usecase/plan-recipe.ts:F19 · components/cook/done-shell.tsx (F 미부여)",
  "M3 · M7", "FN03 · FN04 · FN05 · FN12 기록 / FN06 · FN07 조회",
  "lib/usecase/plan-recipe.ts:F16"),
 ("D1-4", "localStorage", "cookpilot.recipe-shelf", "저장 레시피 목록",
  "완료한 레시피 항목 목록", "ShelfBook 배열",
  "lib/usecase/keep-recipe-shelf.ts:F10",
  "lib/usecase/keep-recipe-shelf.ts:F2",
  "lib/usecase/keep-recipe-shelf.ts:F12 · F4 · components/pick/pick-rail.tsx:F12",
  "M7", "FN12 기록 · 조회 · 삭제 / FN13 조회",
  "lib/usecase/keep-recipe-shelf.ts:F7"),
 ("D1-5", "localStorage", "cookpilot.comments", "예시 게시글 댓글",
  "테이블에 없는 예시 게시글 16건 전용 댓글", "LocalComment 배열",
  "lib/usecase/discuss-post.ts:F1", "lib/usecase/discuss-post.ts:F9", "확인 필요",
  "M5", "FN08 기록 · 조회", "components/post/post-talk.tsx:F5"),
 ("D1-6", "localStorage", "cookpilot.chat-id", "진행 중 대화 ID",
  "이어 붙일 상담 대화 세션 ID", "uuid 문자열 1건",
  "lib/usecase/ask-kitchen.ts:F13", "lib/usecase/ask-kitchen.ts:F12",
  "lib/usecase/ask-kitchen.ts:F14 · components/ask/ask-shell.tsx:F18",
  "M6", "FN11 기록 · 조회 · 삭제", "lib/adapter/browser-chat-id-store.ts:F2"),

 ("D2-1", "Supabase Table", "profiles", "프로필",
  "표시 이름과 프로필 이미지 URL. 가입 트리거가 행을 생성한다",
  "display_name · avatar_url",
  "lib/adapter/supabase-profile-gateway.ts:F1 · F6",
  "lib/adapter/supabase-post-reader.ts:F7 · app/community/page.tsx:F1", "확인 필요",
  "M2", "FN02 · FN10 기록 / FN07 · FN08 · FN13 조회",
  "lib/adapter/supabase-profile-gateway.ts:F1"),
 ("D2-2", "Supabase Table", "posts", "게시글",
  "커뮤니티 게시글 본문과 메타데이터",
  "제목 · 요약 · 본문 · 카테고리(태그) · 표지 URL · like_count · published",
  "lib/adapter/supabase-post-gateway.ts:F3 · F5 · F8",
  "lib/adapter/supabase-post-reader.ts:F6 · F11 · F19",
  "lib/adapter/supabase-post-gateway.ts:F11",
  "M5", "FN07 기록 / FN08 · FN09 · FN13 조회",
  "lib/adapter/supabase-post-gateway.ts:F3"),
 ("D2-3", "Supabase Table", "post_likes", "좋아요",
  "게시글 좋아요 기록. 트리거가 posts.like_count 를 갱신한다", "(post_id, user_id)",
  "lib/adapter/supabase-reaction-gateway.ts:F4",
  "lib/adapter/supabase-reaction-gateway.ts:F6",
  "lib/adapter/supabase-reaction-gateway.ts:F4",
  "M5", "FN09 기록 · 조회 · 삭제",
  "supabase/migrations/20260824090000_likes_bookmarks_comments_avatars.sql"),
 ("D2-4", "Supabase Table", "post_bookmarks", "즐겨찾기",
  "본인만 조회한다. 집계하지 않는다", "(post_id, user_id)",
  "lib/adapter/supabase-reaction-gateway.ts:F4",
  "lib/adapter/supabase-reaction-gateway.ts:F6",
  "lib/adapter/supabase-reaction-gateway.ts:F4",
  "M5", "FN09 기록 · 조회 · 삭제",
  "supabase/migrations/20260824090000_likes_bookmarks_comments_avatars.sql"),
 ("D2-5", "Supabase Table", "post_comments", "댓글",
  "게시글 댓글. 삭제 권한은 RLS 정책이 판정한다",
  "게시글 ID · 작성자 · 본문 · 수정 시각",
  "lib/adapter/supabase-comment-gateway.ts:F5 · F8",
  "lib/adapter/supabase-post-reader.ts:F14",
  "lib/adapter/supabase-comment-gateway.ts:F12",
  "M5", "FN08 기록 · 조회 · 삭제", "lib/adapter/supabase-comment-gateway.ts:F2"),
 ("D2-6", "Supabase Table", "chats", "대화 세션",
  "AI 요리 상담 대화 단위", "대화 세션 1건",
  "lib/adapter/supabase-chat-log.ts:F5", "확인 필요", "확인 필요",
  "M6", "FN11 기록", "lib/adapter/supabase-chat-log.ts:F5"),
 ("D2-7", "Supabase Table", "messages", "대화 메시지",
  "질문과 응답. 테이블을 직접 조회하지 않고 RPC 함수로 읽는다", "role · content",
  "lib/adapter/supabase-chat-log.ts:F6",
  "lib/adapter/supabase-chat-log.ts:F7 (rpc chat_messages)", "확인 필요",
  "M6", "FN11 기록 · 조회", "app/api/chat/[id]/route.ts:F3"),

 ("D3-1", "Supabase Storage", "post-covers", "게시글 표지 이미지",
  "브라우저에서 직접 업로드한다", "png (<uuid>/<시각>.png)",
  "lib/adapter/browser-cover-upload.ts:F6",
  "posts.image_url 을 통해 화면이 렌더링", "확인 필요",
  "M5", "FN07 기록 / FN07 · FN13 조회", "lib/adapter/browser-cover-upload.ts:F3"),
 ("D3-2", "Supabase Storage", "avatars", "프로필 이미지",
  "브라우저에서 256px webp 로 축소해 직접 업로드한다", "webp (<uuid>/<시각>.webp)",
  "lib/adapter/browser-avatar-upload.ts:F9",
  "profiles.avatar_url 을 통해 화면이 렌더링", "확인 필요",
  "M2", "FN10 기록 / FN07 · FN08 · FN13 조회",
  "lib/adapter/browser-avatar-upload.ts:F6"),

 ("D4-1", "External API", "generativelanguage.googleapis.com",
  "Gemini REST generateContent", "브라우저가 서버를 거치지 않고 직접 호출한다",
  "responseSchema 기반 JSON 응답",
  "lib/adapter/gemini-recipe-gateway.ts:F6", "동일", "해당 없음",
  "M3", "FN03 · FN04 · FN05", "lib/adapter/gemini-recipe-gateway.ts:F5"),
 ("D4-2", "External API", "generativelanguage.googleapis.com",
  "Gemini Live WebSocket", "브라우저가 서버를 거치지 않고 직접 연결한다",
  "실시간 오디오 조각 · 전사 텍스트",
  "lib/adapter/gemini-live-gateway.ts:F3 · F20", "동일", "해당 없음",
  "M4", "FN06", "lib/adapter/gemini-live-gateway.ts:F1"),
 ("D4-3", "External API", "generativelanguage.googleapis.com",
  "Gemini 임베딩 · 응답 생성", "Next Server 가 호출한다. 브라우저가 전달한 Key 를 사용",
  "응답 본문", "lib/adapter/langchain-rag.ts:F29", "동일", "해당 없음",
  "M6", "FN11", "lib/adapter/langchain-rag.ts:F22"),
 ("D4-4", "External API", "Pinecone", "후기 벡터 색인",
  "Next Server 가 호출한다. Key 가 서버에만 있어 이 경로만 서버를 경유한다",
  "유사도 상위 5건",
  "lib/adapter/langchain-rag.ts:F13", "lib/adapter/langchain-rag.ts:F28", "확인 필요",
  "M6", "FN11", "lib/adapter/langchain-rag.ts:F10"),
 ("D4-5", "External API", "i.ytimg.com", "YouTube 썸네일",
  "URL 생성만 하고 요청은 img 태그가 수행한다", "썸네일 이미지",
  "해당 없음", "lib/domain/recipe.ts:F30", "해당 없음",
  "M3", "FN04", "lib/domain/recipe.ts:F30"),
 ("D4-6", "External API", "naver · coupang · kurly · ssg", "쇼핑몰 검색",
  "URL 생성 후 사용자가 새 창으로 연다", "검색 URL",
  "해당 없음", "lib/domain/shopping.ts:F2 · F4", "해당 없음",
  "M3", "FN03 계열의 /shop", "lib/domain/shopping.ts:F2"),
 ("D4-7", "Browser Memory", "speechSynthesis", "브라우저 음성 합성",
  "내장 기능이며 외부 서버가 아니다. 낭독 3순위 경로", "합성 음성",
  "해당 없음", "lib/adapter/browser-speech.ts:F13", "해당 없음",
  "M4", "FN06", "lib/adapter/browser-speech.ts:F8"),
]

# ── 07_화면여정 ─────────────────────────────────────────
# (화면ID, Route, 화면명, 진입조건, 입력데이터, 주요기능, 다음화면, 전달데이터,
#  분기조건, 이전/복귀경로, 관련기능, 근거)
SCREENS = [
 ("J1", "/", "소개 화면", "제한 없음", "없음", "서비스 소개",
  "/login · /start · /community", "없음", "사용자 선택", "확인 필요", "—",
  "app/page.tsx"),
 ("J1", "/login", "로그인", "제한 없음", "이메일 · 비밀번호", "FN02 로그인",
  "/start · /signup", "인증 쿠키", "인증 성공 여부", "확인 필요", "FN02",
  "app/actions/auth.ts:F7"),
 ("J1", "/signup", "회원가입", "제한 없음",
  "표시 이름 · 이메일 · 비밀번호 · 비밀번호 확인", "FN02 회원가입", "/start", "인증 쿠키",
  "메일 확인 필요 여부", "확인 필요", "FN02", "app/actions/auth.ts:F13"),
 ("J1", "/start", "API Key 입력", "제한 없음", "Gemini API Key", "FN01",
  "/community · /start/model", "D1-1", "저장 성공 여부", "확인 필요", "FN01",
  "components/start/api-key-form.tsx:F5"),
 ("J2", "/start/model", "음성 모델 선택", "제한 없음", "음성 성별 · 말투 · 응답 속도",
  "기능 목록 외 공통 단계", "/pick", "D1-2", "없음", "확인 필요", "FN06",
  "components/setup/setup-picker.tsx:F15"),
 ("J2 · J3", "/community", "홈 · 커뮤니티 목록", "제한 없음", "?tab= · ?q=",
  "FN13 목록 · 검색 · 태그", "/posts/[id] · /pick · /start · /start/model · /ask · /shelf · /account",
  "게시글 ID · 검색어",
  "API Key 존재 여부 → /start, 음성 모델 선택 여부 → /start/model",
  "확인 필요", "FN13 · FN09", "components/community/home-me.tsx:F7 · F8"),
 ("J2", "/pick", "레시피 입력 방식 선택", "제한 없음",
  "음성 · YouTube URL · 보유 재료", "FN03 · FN04 · FN05", "/shop", "D1-3",
  "입력 방식 3종", "/cook/done 에서 임시 레시피 삭제 후 재진입",
  "FN03 · FN04 · FN05", "components/pick/pick-cards.tsx:F8"),
 ("J2", "/shop", "장보기 목록 확인", "D1-3 에 레시피 존재", "D1-3", "장보기 목록 · 쇼핑몰 검색",
  "/cook", "D1-3", "레시피 미선택 시 '요리 고르러 가기' 표시", "확인 필요",
  "FN03 계열", "components/shop/shop-shell.tsx:F8"),
 ("J2", "/cook", "음성 기반 요리 진행", "D1-3 에 레시피 존재", "D1-1 · D1-2 · D1-3",
  "FN06", "/cook/done · /shop", "D1-3",
  "API Key 미보유 시 현재 화면에서 오류 메시지 표시", "/shop 링크",
  "FN06", "components/cook/live-console.tsx:F13"),
 ("J2", "/cook/done", "요리 완료", "D1-3 에 레시피 존재", "D1-3",
  "FN12 저장 · 표지 이미지 생성 · 다음 요리 선택",
  "/write?from=cook · /shelf · /pick", "D1-4 · D1-3(삭제)",
  "레시피 미선택 시 안내 표시", "/pick 으로 되돌아갈 때 D1-3 삭제",
  "FN07 · FN12", "components/cook/done-shell.tsx:F6"),
 ("J3", "/posts/[id]", "게시글 상세", "제한 없음", "게시글 ID",
  "FN08 댓글 · FN09 좋아요 · 즐겨찾기 · 레시피로 요리",
  "/posts/[id]/edit · /shop · /start · /login", "게시글 ID · D1-3",
  "본인 게시글 여부 → 수정 버튼, 로그인 여부 → 댓글 폼", "확인 필요",
  "FN08 · FN09 · FN13", "components/post/post-actions.tsx:F5"),
 ("J4 · J7", "/write", "게시글 작성", "로그인 상태", "제목 · 요약 · 본문 · 태그 · 표지 이미지",
  "FN07 작성", "/posts/<id> · /community", "D2-2 · D3-1", "검증 통과 여부",
  "취소 시 /community", "FN07", "app/write/page.tsx:F4"),
 ("J4 · J7", "/posts/[id]/edit", "게시글 수정", "로그인 상태 + 본인 게시글",
  "제목 · 요약 · 본문 · 태그 · 표지 이미지", "FN07 수정", "/posts/<id>", "D2-2",
  "타 사용자 게시글이면 /posts/<id> 로 이동", "취소 시 /posts/<id>", "FN07",
  "app/posts/[id]/edit/page.tsx:F3 · F6"),
 ("J5", "/ask", "AI 요리 상담", "제한 없음", "질문 문자열 · D1-1", "FN11 질의응답",
  "/posts/[id] (근거 후기)", "D1-6 · D2-7", "질문 검증 · 검색 결과 유무",
  "화면 이동 없음", "FN11", "components/ask/ask-shell.tsx:F8"),
 ("J6", "/shelf", "저장 레시피", "제한 없음", "D1-4", "FN12 조회 · 재사용 · 삭제 · 백업",
  "/shop", "D1-3", "레시피 미포함 항목은 비활성화", "확인 필요", "FN12",
  "components/shelf/shelf-stand.tsx:F6"),
 ("J7", "/account", "계정 설정", "로그인 상태", "표시 이름 · 이미지 파일",
  "FN10 프로필 관리", "화면 이동 없음", "D2-1 · D3-2", "검증 통과 여부",
  "확인 필요", "FN10", "app/account/page.tsx:F3"),
 ("확인 필요", "/community2", "디자인 시안 비교 화면", "제한 없음", "없음", "해당 없음",
  "없음", "없음", "없음", "없음", "—", "app/community2/page.tsx"),
]
